/* eslint-disable @next/next/no-img-element */
import React from "react";
import Head from "next/head";
import styles from "./styles.module.scss";
import { Swiper, SwiperSlide } from "swiper/react";
import SwiperCore, { Autoplay, Pagination } from "swiper";
import {
  FaLaptop,
  FaProjectDiagram,
  FaFlask,
  FaCode,
  FaChartBar,
  FaClock,
  FaSyncAlt,
  FaBullseye,
  FaDesktop,
  FaEnvelopeOpen,
  FaBuilding,
} from "react-icons/fa";

import Mouse from "../../components/Mouse";

SwiperCore.use([Autoplay, Pagination]);

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pollux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.content}>
        <section id="inicio" className={styles.presentation}>
          <Swiper slidesPerView={1} autoplay={{ delay: 4000 }} loop={true}>
            <SwiperSlide>
              <div className={styles.container}>
                <div className={styles.message}>
                  <p className={styles.subTitle}>polux better for</p>
                  <h1 className={styles.title}>
                    digital <br /> transformation
                  </h1>
                  <p className={styles.text}>
                    Projetos inovadores que trazem resultados
                  </p>
                </div>
                <div className={styles.imageContainer}>
                  <img
                    className={styles.image}
                    src="/laptop.png"
                    alt="Pollux"
                  />
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className={styles.container}>
                <div className={styles.message}>
                  <p className={styles.subTitle}>polux better for</p>
                  <h1 className={styles.title}>innovation</h1>
                  <p className={styles.text}>
                    Projetos inovadores que trazem resultados
                  </p>
                </div>
                <div className={styles.imageContainer}>
                  <img
                    className={styles.image}
                    src="/smartphone.png"
                    alt="Pollux"
                  />
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className={styles.container}>
                <div className={styles.message}>
                  <p className={styles.subTitle}>polux better for</p>
                  <h1 className={styles.title}>business</h1>
                  <p className={styles.text}>
                    Projetos inovadores que trazem resultados
                  </p>
                </div>
                <div className={styles.imageContainer}>
                  <img
                    className={styles.image}
                    src="/laptop.png"
                    alt="Pollux"
                  />
                </div>
              </div>
            </SwiperSlide>
          </Swiper>
          <Mouse />
        </section>
        <section id="sobre" className={styles.sobreNos}>
          <img className={styles.homemimage} src="img-homem.png" alt="Pollux" />
          <div className={styles.texts}>
            <h1 className={styles.titleSobreNos}>
              A Pollux<span className={styles.span}>.</span>
            </h1>
            <span className={styles.subtitle}>Talento e dedicação</span>
            <p className={styles.paragrafo}>
              Somos uma empresa jovem, com pessoas experientes. Profissionais
              com uma média de 17 anos na indústria de TI e Comunicação.
            </p>
            <p className={styles.paragrafo}>
              Formamos uma equipe onde a combinação de nossos talentos resulta
              em muito mais que aplicativos, jogos, sites, gamification,
              internet das coisas ou qualquer outra coisa que envolva bits e
              bytes.
            </p>
            <div className={styles.sitacaoContainer}>
              <h5 className={styles.sitacao}>
                <img
                  className={styles.imgSitacao}
                  src="Sitação.png"
                  alt="Pollux"
                />
                Para as agências de publicidade, oferecemos uma equipe altamente
                qualificada para implementar o que precisam. Já para os
                clientes, entendemos suas necessidades e tiramos do papel os
                seus produtos digitais.
              </h5>
            </div>
          </div>
        </section>
        <section className={styles.solucoes}>
          <div className={styles.itens}>
            <div className={styles.itemContainer}>
              <div className={styles.itemTitle}>
                <FaLaptop />
                <h3 className={styles.titleItem}>Negócios e Serviços</h3>
              </div>
              <p className={styles.description}>
                Concepção e validação de modelos de Negócios e Desenho de
                Jornadas de Usuários segundo preceitos de Design.
              </p>
            </div>
            <div className={styles.itemContainer}>
              <div className={styles.itemTitle}>
                <FaProjectDiagram />
                <h3 className={styles.titleItem}>Processos de Apoio</h3>
              </div>
              <p className={styles.description}>
                Toda Jornada de usuário é sustentada por processos de Backstage
                que precisam ser modelados e monitorados.
              </p>
            </div>
            <div className={styles.itemContainer}>
              <div className={styles.itemTitle}>
                <FaFlask />
                <h3 className={styles.titleItem}>Inovação</h3>
              </div>
              <p className={styles.description}>
                Pesquisa & Desenvolvimento de estratégias de aplicação de novas
                techs é nosso dia-a-dia.
              </p>
            </div>
            <div className={styles.itemContainer}>
              <div className={styles.itemTitle}>
                <FaCode />
                <h3 className={styles.titleItem}>Programação</h3>
              </div>
              <p className={styles.description}>
                Execução de projetos de especificação, construção, implantação e
                manutenção de sistemas.
              </p>
            </div>
            <div className={styles.itemContainer}>
              <div className={styles.itemTitle}>
                <FaChartBar />
                <h3 className={styles.titleItem}>Análise de Dados</h3>
              </div>
              <p className={styles.description}>
                Torna o cliente data-driven com a definição de KPIs,
                estruturação de modelos de dados e adoção de ferramentas para
                sua análise.
              </p>
            </div>
            <div className={styles.itemContainer}>
              <div className={styles.itemTitle}>
                <FaClock />
                <h3 className={styles.titleItem}>Cultura Ágil</h3>
              </div>
              <p className={styles.description}>
                Preparação do cliente para adoção da Cultura Ágil (não
                importando a área), partindo da visão tradicional em silos.
              </p>
            </div>
            <div className={styles.itemContainer}>
              <div className={styles.itemTitle}>
                <FaSyncAlt />
                <h3 className={styles.titleItem}>Modernização</h3>
              </div>
              <p className={styles.description}>
                Atualização do parque de equipamentos e de sistemas de clientes.
              </p>
            </div>
            <div className={styles.itemContainer}>
              <div className={styles.itemTitle}>
                <FaBullseye />
                <h3 className={styles.titleItem}>Planejamento de Marca</h3>
              </div>
              <p className={styles.description}>
                Apoio ao Planejamento da Identidade de Marca e ao Growth
                Hacking, enquanto importantes componentes do Digital.
              </p>
            </div>
            <div className={styles.itemContainer}>
              <div className={styles.itemTitle}>
                <FaDesktop />
                <h3 className={styles.titleItem}>Soluções Multicanais</h3>
              </div>
              <p className={styles.description}>
                Construção de Soluções orientadas aos usuários, com serviços
                entregues de maneira uniforme e cross-channel.
              </p>
            </div>
          </div>
        </section>
        <section id="clientes" className={styles.marcas}>
          <Swiper
            spaceBetween={50}
            slidesPerView={3}
            autoplay={{ delay: 4000 }}
            loop={true}
            pagination={{ clickable: true }}
            breakpoints={{
              300: {
                slidesPerView: 1,
              },
              470: {
                slidesPerView: 1,
              },
              640: {
                slidesPerView: 2,
              },
              768: {
                slidesPerView: 3,
              },
            }}
          >
            <SwiperSlide>
              <img
                className={styles.imageMarcas}
                src="logo-bank.jpg"
                alt="Pollux"
              />
            </SwiperSlide>
            <SwiperSlide>
              <img
                className={styles.imageMarcas}
                src="logo-bmg.png"
                alt="Pollux"
              />
            </SwiperSlide>
            <SwiperSlide>
              <img
                className={styles.imageMarcas}
                src="logo-bradesco.png"
                alt="Pollux"
              />
            </SwiperSlide>
            <SwiperSlide>
              <img
                className={styles.imageMarcas}
                src="logo-itau.png"
                alt="Pollux"
              />
            </SwiperSlide>
            <SwiperSlide>
              <img
                className={styles.imageMarcas}
                src="logo-panvel.png"
                alt="Pollux"
              />
            </SwiperSlide>
            <SwiperSlide>
              <img
                className={styles.imageMarcas}
                src="logo-ubisoft.png"
                alt="Pollux"
              />
            </SwiperSlide>
          </Swiper>
        </section>
        <section id="contatos" className={styles.faleConosco}>
          <div className={styles.texts}>
            <h1 className={styles.titleContatos}>
              Encontre & Realize<span className={styles.span}>.</span>
            </h1>
            <div className={styles.contatos}>
              <div className={styles.item}>
                <FaEnvelopeOpen />
                <span className={styles.text}>contato@pollu-x.tech</span>
              </div>
              <div className={styles.item}>
                <FaBuilding />
                <span className={styles.text}>
                  R. Fernando Amaro, 60 - Alto da XV, Curitiba - PR, 80045-080
                </span>
              </div>
              <div className={styles.map}>
                <a
                  href="https://www.google.com/maps/place/R.+Fernando+Amaro,+60+-+Alto+da+XV,+Curitiba+-+PR,+80045-080/@-25.4285549,-49.2599994,17z/data=!3m1!4b1!4m5!3m4!1s0x94dce446df50ba8f:0xcdf69f130cba9ab8!8m2!3d-25.4285549!4d-49.2578107"
                  target="_blank"
                  rel="noreferrer"
                >
                  <img className={styles.img} src="map.png" alt="Pollux" />
                </a>
              </div>
            </div>
          </div>
          <div className={styles.cta}>
            <h2 className={styles.titleCta}>
              Tem um novo projeto<span className={styles.spanCta}>?</span>
            </h2>
            <h4 className={styles.textCta}>
              Uma longa viagem começa com um único passo.
            </h4>
            <a
              href="https://api.whatsapp.com/send?phone=5519996238785"
              target="_blank"
              rel="noreferrer"
            >
              ENTRAR EM CONTATO
            </a>
          </div>
        </section>
      </main>
    </div>
  );
}
